<?php /** @var $this Mage_Core_Block_Template */ ?>
<?php $_product = $this->getProduct(); ?>
<?php if($_product->isSaleable()): ?>
<label for="qty-<?php echo $_product->getId() ?>"><?php echo $this->__('Qty:') ?></label>
<select name="qty" id="qty-<?php echo $_product->getId() ?>" title="<?php echo $this->__('Qty') ?>" class="qty">
    <option value="1" selected>1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
    <option value="6">6</option>
    <option value="7">7</option>
    <option value="8">8</option>
    <option value="9">9</option>
    <option value="10">10</option>
</select>
<?php endif; ?>
