<?php
/** @var Mage_Catalog_Block_Product_View_Type_Configurable $this */
$_product    = $this->getProduct();
$_color = $this->getColor();
$_attributes = Mage::helper('core')->decorateArray($this->getAllowAttributes());
$_productViewBlock = $this->getLayout()->createBlock('codekunst_looks/product_view');
?>
<?php if ($_product->isSaleable() && count($_attributes)):?>
    <dl>
        <?php foreach($_attributes as $_attribute): ?>
            <?php if($_attribute->getAttributeId() == 262 /* Color Attribute Id */): ?>
                <dt></dt>
                <dd>
                    <input type="hidden" name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]" value="<?php echo $_color ?>"/>
                </dd>
            <?php else: ?>
                <dt><label class="required" style="display:block"><em>*</em><?php echo $_attribute->getLabel() ?></label></dt>
                <dd<?php if ($_attribute->decoratedIsLast){?> class="last"<?php }?>>
                    <div class="input-box">
                        <select name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]" id="attribute<?php echo $_attribute->getAttributeId() ?>_<?php echo $_product->getId() ?>" class="required-entry super-attribute-select_<?php echo $_product->getId() ?> super-attribute-select">
                            <option><?php echo $this->__('Choose an Option...') ?></option>
                        </select>
                    </div>
                </dd>
            <?php endif; ?>
        <?php endforeach; ?>
    </dl>
    <script type="text/javascript">
        <?php $json = (get_class($this) == "OrganicInternet_SimpleConfigurableProducts_Block_Catalog_Product_View_Type_Configurable" ||
        in_array("OrganicInternet_SimpleConfigurableProducts_Block_Catalog_Product_View_Type_Configurable", class_parents(get_class($this)))) ? $this->getUpsellJsonConfig() : $this->getJsonConfig(); ?>
        var config_<?php echo $_product->getId() ?> = <?php echo $json ?>;
        config_<?php echo $_product->getId() ?>.containerId = "upsell-product-<?php echo $_product->getId() ?>";
        spConfigs[<?php echo $_product->getId() ?>] = new Codekunst_UpsellProduct.Config(config_<?php echo $_product->getId() ?>);

        optionsPrices[<?php echo $_product->getId() ?>] = new Product.OptionsPrice(<?php echo $_productViewBlock->getJsonConfig($_product) ?>);
    </script>
<?php endif;?>
