<script type="text/javascript">
document.observe('dom:loaded', function(){
	<?php foreach ($this->getPaymentMethods() as $paymentCode) : ?>
		cwpm_<?php echo $paymentCode ?> = new Customweb.SaferpayCw(
			'<?php echo $this->getHiddenFieldsUrl() ?>',
			'<?php echo $this->getVisibleFieldsUrl() ?>',
			'<?php echo $this->getAuthorizeUrl() ?>',
			'<?php echo $this->getJavascriptUrl() ?>',
			'<?php echo $this->getSaveShippingMethodUrl() ?>',
			'<?php echo $paymentCode ?>'
		);
	<?php endforeach; ?>

	<?php if ($this->isPreload()) : ?>
		new Customweb.CheckoutPreload('<?php echo $this->getPreloadUrl() ?>');
	<?php endif; ?>
});
</script>