<?php
/*
    code originally posted by Inchoo.net
    http://inchoo.net/magento/how-to-implement-relprev-and-relnext-to-magentos-pagination/
*/
?>
<?php
$actionName = $this->getAction()->getFullActionName();
if ($actionName == 'catalog_category_view') // Category Page
{
    $category = Mage::registry('current_category');
    /** @var Mage_Catalog_Model_Resource_Product_Collection $prodCol */
    $prodCol = $this->getLayout()->getBlock("product_list")->getLoadedProductCollection();
    /** @var Mage_Page_Block_Html_Pager $tool */
    $tool = Mage::app()->getLayout()->createBlock('page/html_pager')->setLimit(Mage::app()->getLayout()->createBlock('catalog/product_list_toolbar')->getLimit())->setCollection($prodCol);
    $linkPrev = false;
    $linkNext = false;
    if ($tool->getCollection()->getSelectCountSql()) {
        if ($tool->getLastPageNum() > 1) {
            if (!$tool->isFirstPage()) {
                $linkPrev = true;
                if ($tool->getCurrentPage() == 2) {
                    $url = explode('?', $tool->getPreviousPageUrl());
                    $prevUrl = @$url[0];
                }
                else {
                    $prevUrl = $tool->getPreviousPageUrl();
                }
            }
            if (!$tool->isLastPage()) {
                $linkNext = true;
                $nextUrl = $tool->getNextPageUrl();
            }
        }
    }
    if ($linkPrev) echo '<link rel="prev" href="' . $prevUrl . '" />';
    if ($linkNext) echo '<link rel="next" href="' . $nextUrl . '" />';
    if ($linkPrev) echo '<meta name="robots" content="noindex">';
    if (!$linkPrev) echo '<meta name="robots" content="index,follow">';
}
