<div class="bla">
	<?php
	$postdata = http_build_query(
		array(
			'view' => 'content'
		)
	);

	//$proxy = 'tcp://proxy.fra1.compute.cloud.idnt.net';

	$ch = curl_init();

	curl_setopt($ch, CURLOPT_POST, 1);
	curl_setopt($ch, CURLOPT_POSTFIELDS, $postdata);

	curl_setopt($ch, CURLOPT_URL, 'http://www.mey.com/var/export/scripttest.php');
	curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

	//curl_setopt($ch, CURLOPT_PROXYAUTH, CURLAUTH_NTLM);
	//curl_setopt($ch, CURLOPT_PROXY, $proxy);
	//curl_setopt($ch, CURLOPT_PROXYPORT, 8080);

	curl_setopt($ch, CURLOPT_TIMEOUT, 20);
	curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 20);

	$content = curl_exec($ch);
	$info = curl_getinfo($ch);
	$error = curl_error($ch);

	curl_close($ch);
	print_r(json_decode(json_decode($content,true)['content'],true)['content']);

	?>
</div>