<?php

class
MageB2B_Sublogin_Block_Admin_Acl_Grid
extends
Mage_Adminhtml_Block_Widget_Grid
{

public
function
__construct()
{
parent::__construct();
$this->setId('aclGrid');
$this->setDefaultSort('acl_id');
$this->setDefaultDir('ASC');
$this->setSaveParametersInSession(true);
$this->setUseAjax(true);
}
public
function
getGridUrl()
{
return
$this->getUrl('*/*/grid',
array('_current'=>true));
}

protected
function
_prepareCollection()
{
$_205d95c001c842f933e3b55fa4e902d5d2fdd0af
=
Mage::getModel('sublogin/acl')->getCollection();
$this->setCollection($_205d95c001c842f933e3b55fa4e902d5d2fdd0af);
return
parent::_prepareCollection();
}

protected
function
_prepareColumns()
{
$this->addColumn('acl_id',
array(
'header'
=>
Mage::helper('sublogin')->__('ID'),
'align'
=>'right',
'width'
=>
'50px',
'index'
=>
'acl_id',
));
$this->addColumn('name',
array(
'header'
=>
Mage::helper('sublogin')->__('Name'),
'index'
=>
'name',
));
$this->addColumn('identifier',
array(
'header'
=>
Mage::helper('sublogin')->__('Identifier'),
'index'
=>
'identifier',
));
return
parent::_prepareColumns();
}

public
function
getRowUrl($_15ded6f30a13ef74e4a6288cd249a3be115e0ad0)
{
return
$this->getUrl('*/*/edit',
array('id'
=>
$_15ded6f30a13ef74e4a6288cd249a3be115e0ad0->getId()));
}

protected
function
_prepareMassaction()
{
$this->setMassactionIdField('acl_id');
$this->getMassactionBlock()->setFormFieldName('acl_ids');
$this->getMassactionBlock()->addItem('delete',
array(
'label'
=>
Mage::helper('sublogin')->__('Delete'),
'url'
=>
$this->getUrl('*/*/massDelete'),
'confirm'
=>
Mage::helper('sublogin')->__('Are you sure?')
));
return
$this;
}
}